AuthApp/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path("" , views.signup , name="signup"),
    path("projects/ExpenseTracker/login" , views.login_user , name="login"),
    path("projects/ExpenseTracker/logout" , views.logout_user  , name="logout"),
    path("projects/ExpenseTracker/delete" , views.delete_user  , name="delete"),
]

ExpenseProject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings # new
from  django.conf.urls.static import static #new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/ExpenseTracker/User/' , include('AuthApp.urls')),
    path("projects/ExpenseTracker/" , include('BaseApp.urls')),
    path("convert/", include("guest_user.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

BaseApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError

# Create your models here.

class baseMoney(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.IntegerField(null=True, blank=True)
    Bank_Account = 'Bank Account'
    Credit_Card = 'Credit Card'
    Cash = 'Cash'

    Account_choices = [
        (Bank_Account, 'Bank Account'),
        (Credit_Card, 'Credit Card'),
        (Cash, 'Cash'),
    ]

    typeofacc = models.CharField(max_length=20 , choices=Account_choices , default=Cash)
    limit = models.IntegerField(null=True, blank=True)
    spent = models.IntegerField(blank=True , default=0)

    def __str__(self):
        return self.name 


class incomeSource(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.IntegerField()
    creditedIn = models.ForeignKey(baseMoney , on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.name

class expenseSource(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.IntegerField()
    debitedFrom = models.ForeignKey(baseMoney , on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    time = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.name

templates/finance/accounts.html
{% extends "homePage.html" %}
{% load static %}

{% block title %}Account{% endblock title %}


{% block style %}
    <link href="{% static "css/expopop.css" %}" rel="stylesheet">
    <link href="{% static "css/incopop.css" %}" rel="stylesheet">
{% endblock style %}


{% block head %}
<nav class="bg-gray-800 p-4">
    <div class=" flex justify-between flex-grow container items-center lg:mx-auto md:mx-auto sm:pl-20">
        <div class="text-white text-2xl font-bold">Accounts:</div>
        <div class="flex justify-center space-x-8" >
            <a href="#" onclick="popupFn()" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add Account</a>
        </div>
    </div>
</nav>
{% endblock head %}



{% block content %}
<div class="bg-white shadow-md rounded-lg p-5 mb-5">
    <h2 class="text-2xl font-semibold mb-4">Cash:</h2>
    {% for money in cash %}
    <div class="bg-gray-200 shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">{{money.name}}</h2>
    <div class="flex items-center justify-between mb-2">
        <div class="flex-1">
            <h4 class="text-xl font-semibold">Amount: {{money.amount}}</h4>
        </div>
        <div class="text-right">
            <a href="{% url 'delete-baseMoney' money.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a>
        </div>
    </div>
    </div>
    {% endfor %}
</div>
<div class="bg-white shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">Bank Accounts:</h2>
    {% for account in bankAcc %}
    <div class="bg-gray-200 shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">{{account.name}}</h2>
    <div class="flex items-center justify-between mb-2">
        <div class="flex-1">
            <h4 class="text-xl font-semibold">Amount: {{account.amount}}</h4>
        </div>
        <div class="text-right">
            <a href="{% url 'delete-baseMoney' account.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a>
        </div>
    </div>
    </div>
    {% endfor %}
</div>
<div class="bg-white shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">Credit cards:</h2>
    {% for credit in creditcard %}
    <div class="bg-gray-200 shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">{{credit.name}}</h2>
    <div class="flex items-center justify-between mb-2">
        <div class="flex-1">
            <h4 class="text-xl font-semibold">Limit: {{credit.limit}}</h4>
            <h4 class="text-xl font-semibold">Spent: {{credit.spent}}</h4>
        </div>
        <div class="text-right">
            <a href="{% url 'reset-spent' credit.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Reset</a>
            <a href="{% url 'delete-baseMoney' credit.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a>
        </div>
    </div>
    </div>
    {% endfor %}
</div>


{% endblock content %}

{% block popup %}

<div id="popupDialog" class="relative p-4 w-full max-w-md max-h-full bg-gray-100">
    {% include "finance/addaccount.html" %}
</div>

<script src="{% static 'js/expopop.js' %}"></script>
{% endblock popup %}

templates/finance/addExpense.html
<div class="flex bg-gray-200 items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Add Expense
                </h3>
                <button type="button" onclick="closeFn()" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-l w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
                    X
                </button>
            </div>
            <!-- Modal body -->
            <form action="{% url "expenseSource" %}" method="POST" class="p-4 md:p-5">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 grid-cols-2">
                    <div class="col-span-2">
                        <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
                        <input type="text" name="name" id="id_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type Expense name" required>
                    </div>
                    
                    <div class="col-span-2 sm:col-span-1">
                        <label for="id_debitedFrom" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Debited From:</label>
                        <select  name="debitedFrom" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
                        {% for account in accounts %}
                        <option value="{{account.id}}">{{account.name}}</option>
                        {% endfor %} 
                        </select>
                    </div>
                </div>
                    <div id="amount-field" class="col-span-2 sm:col-span-1">
                        <label for="id_amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
                        <input type="number" min="0" step=".01" id="amount" name="amount" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
                    </div>
                    <div id="date-field" class="col-span-2 sm:col-span-1">
                        <label for="id_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Date:</label>
                        <input type="text" id="id_date" name="date" value="{{today_date}}" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
                    </div>
                    <div class="pt-4">
                <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Add new Expense
                </button>
                    </div>
            </form>
        </div>
</div>

templates/finance/addaccount.html
       
            <div class="flex bg-gray-200 items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    Create New Account
                </h3>
                <button type="button" onclick="closeFn()" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-l w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
                    X
                </button>
            </div>
            <!-- Modal body -->
            <form action="{% url "baseMoney" %}" method="POST" class="p-4 md:p-5">
                {% csrf_token %}
                <div class="grid gap-4 mb-4 grid-cols-2">
                    <div class="col-span-2">
                        <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
                        <input type="text" name="name" id="name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type Account name" required>
                    </div>
                    
                    <div class="col-span-2 sm:col-span-1">
                        <label for="category" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Category</label>
                        <select id="typeofacc" onchange="displayDiv()" name="typeofacc" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
                            <option value="Bank Account">Bank Account</option>
                            <option value="Cash">Cash</option>
                            <option value="Credit Card">Credit Card</option>
                        </select>
                    </div>
                </div>
                    <div id="amount-field" class="col-span-2 sm:col-span-1">
                        <label for="amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
                        <input type="number" min="0" step=".01" id="amount" name="amount" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                    </div>
                    <div id="limit-field" class=" hidden col-span-2 sm:col-span-1">
                        <label for="limit" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Limit</label>
                        <input type="number" min="0" step=".01" id="limit" name="limit" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                    </div>
                    <div class="pt-4">
                <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                    Add New Account
                </button>
                    </div>
            </form>
        </div>
        
</div>

templates/finance/addincome.html
<div class="flex bg-gray-200 items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
    <h2 class="text-lg font-semibold text-gray-900 dark:text-white">
        Add Income
    </h2>
    <button type="button" onclick="closeincomepopup()" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-l w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white">
        X
    </button>
</div>
<!-- Modal body -->
<form action="{% url "incomeSource" %}" method="POST" class="p-4 md:p-5">
    {% csrf_token %}
    <div class="grid gap-4 mb-4 grid-cols-2">
        <div class="col-span-2">
            <label for="id_name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name</label>
            <input type="text" name="name" id="id_name" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type Income name" required>
        </div>
        
        <div class="col-span-2 sm:col-span-1">
            <label for="id_creditedTo" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Credited To:</label>
            <select  name="creditedTo" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
            {% for account in accounts %}
            <option value="{{account.id}}">{{account.name}}</option>
            {% endfor %} 
            </select>
        </div>
    </div>
        <div id="amount-field" class="col-span-2 sm:col-span-1">
            <label for="id_amount" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Amount</label>
            <input type="number" min="0" step=".01" id="amount" name="amount" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
        </div>
        <div id="date-field" class="col-span-2 sm:col-span-1">
            <label for="id_date" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Date:</label>
            <input type="text" id="id_date" name="date" value="{{today_date}}" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>
        </div>
        <div class="pt-4">
    <button type="submit" class="text-white inline-flex items-center bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Add new Income
    </button>
        </div>
</form>
</div>
</div>

templates/finance/finance.html
{% extends "homePage.html" %}
{% load static %}

{% block title %}Transactions{% endblock title %}

{% block style %}
<link href="{% static "css/expopop.css" %}" rel="stylesheet">
<link href="{% static "css/incopop.css" %}" rel="stylesheet">
{% endblock style %}

{% block head %}
<nav class="bg-gray-800 p-4">
    <div class=" flex justify-between flex-grow container items-center lg:mx-auto md:mx-auto sm:pl-20">
        <div class="text-white text-2xl font-bold">Transactions</div>
        <div class="flex justify-center space-x-4">
            <a href="#" onclick="incomepopup()" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add Income</a>
            <a href="#" onclick="popupFn()" class=" bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Add Expense</a>
        </div>
    </div>
</nav>
{% endblock head %}

{% block content %}

<div class="bg-white shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">Incomes</h2>
    <table class="display alltable responsive nowrap">
        <thead>
            <tr class="bg-gray-800 text-white" align="left">
                <th>Date</th>
                <th>Reason</th>
                <th>Amount</th> 
                <th>Credited To</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for inco in income_page_obj %}
            <tr class="border-b">
                <td>{{ inco.date|date:"d M, Y" }}</td>
                <td>{{ inco.name }}</td>
                <td>{{ inco.amount }}</td>
                <td>{{ inco.creditedIn }}</td>
                <td>
                    <a href="{% url 'delete-income' inco.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div class="bg-white shadow-md rounded-lg p-6 mb-5">
    <h2 class="text-2xl font-semibold mb-4">Expenses</h2>
    <table class="display alltable responsive nowrap">
        <thead>
            <tr class="bg-gray-800 text-white" align="left">
                <th>Date</th>
                <th>Reason</th>
                <th>Amount</th>
                <th>Debited From</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for expo in expense_page_obj %}
            <tr class="border-b">
                <td>{{ expo.date|date:"d M, Y" }}</td>
                <td>{{ expo.name }}</td>
                <td>{{ expo.amount }}</td>
                <td>{{ expo.debitedFrom }}</td>
                <td>
                    <a href="{% url 'delete-expense' expo.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

{% block popup %}
<div id="popupDialog" class="relative p-4 w-full max-w-md max-h-full bg-gray-100 ">
    {% include "finance/addExpense.html" %}
</div>

<div id="popupDialogforincome" class="relative p-4 w-full max-w-md max-h-full bg-gray-100 ">
    {% include "finance/addincome.html" %}
</div>

<script src="{% static 'js/expopop.js' %}"></script>
<script src="{% static 'js/incopop.js' %}"></script>
{% endblock popup %}